name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Gradle Build
        run: ./gradlew build
